name: Deploy Node.js to Azure Web App

on:
  [push]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: dev
    env:
      APP_NAME: rg-dad-dams
      APP_PORT: 8888
      APP_DEBUG: true
      APP_CLUSTER: false
      APP_LOG_LEVEL: debug
      APP_TIMEZONE: Asia/Colombo

      REQ_IDENTIFIER_NAME: UUID
      MS_NAME: base-template
      FILE_LOG_LEVEL: debug
      CONSOLE_LOG_LEVEL: info
      MASSAGE_TYPE_HEADER_NAME: Massage-Type

      DB_MYSQL_HOST: database-dad-dms.mysql.database.azure.com
      DB_MYSQL_DATABASE: db_dad_dms
      DB_MYSQL_USER: dadadmin@database-dad-dms
      DB_MYSQL_PASSWORD: 007@bingoDin
      DB_MYSQL_PORT: 3306

      AZURE_WEBAPP_NAME: web-dad-dms-backend
      AZURE_WEBAPP_PUBLISH_PROFILE: cjlxn0BHBfv9QFy3rHkReMlNeLDmlJrYrCsCnpl5dqvF92dpTCBD85HALmyL
      AZURE_WEBAPP_PACKAGE_PATH: build
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          # Build and test the project, then
          # deploy to Azure Web App.
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  # For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
  # For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
